name: Emscripten

on:
  push:
    branches:
      - master
      - dev
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Clone imgui and hello_imgui
        run: |
          ./scripts/build_utilities.py run -all_imgui_downloads

      - name: Install emscripten
        run: ./scripts/build_utilities.py run -install_emscripten

#      - name: Compile OpenCV (about 12 minutes)
#        run: source ~/emsdk/emsdk_env.sh && ./scripts/build_utilities.py --opencv_build_emscripten

      - name: Download precompiled OpenCV for emscripten
        run: |
          cd external
          wget https://traineq.org/ImmvisionGithubFiles/opencv_install_emscripten.tgz
          tar xfz opencv_install_emscripten.tgz

      - name: Configure
        run: |
            mkdir build_emscripten
            cd build_emscripten
            source ~/emsdk/emsdk_env.sh && ../scripts/build_utilities.py --only_echo_command=False -cmake_emscripten_build

      - name: Build
        working-directory: build_emscripten
        run: |
          make -j 4

      - uses: actions/upload-artifact@v3
        with:
          name: emscripten_bin_artifacts
          path: build_emscripten/bin/
          retention-days: 90
