name: Emscripten

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Install emscripten
        run: ./scripts/emscripten/install_emscripten.sh

      - name: Compile OpenCV
        run: ./scripts/build_utilities.py --opencv_build_emscripten

      - name: Configure
        run: |
            source ~/emsdk/emsdk_env.sh
            mkdir build_emscripten
            cd build_emscripten
            ../scripts/build_utilities.py --cmake_emscripten_build

      - name: Build
        working-directory: build_emscripten
        run: |
          make -j 4
