name: MacOS

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Install third parties
      run: |
          ../scripts/build_utilities.py --install_vcpkg_thirdparties
          ../scripts/build_utilities.py --imgui_download
          ../scripts/build_utilities.py --hello_imgui_download          

    - name: Configure
      run: |
          mkdir build
          cd build
          ../scripts/build_utilities.py --cmake_desktop_build_vcpkg

    - name: Build
      working-directory: build
      run: |
          make
