name: MacOS

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master

    - name: Checkout submodules
      run: git submodule update --init --recursive

    # vcpkg_osx_intel.tgz created with
    # tar --exclude=vcpkg/.git  --exclude=vcpkg/downloads --exclude=vcpkg/buildtrees  -zcvf "vcpkg_osx_intel.tgz" vcpkg
    # Next time, prefer 7z version, created by build_utilities (vcpkg_export)
    - name: Download vcpkg_osx_intel.tgz
      run: |
          cd external
          wget https://traineq.org/ImmvisionGithubFiles/vcpkg_osx_intel.tgz
          tar xfz vcpkg_osx_intel.tgz

    - name: run_build_all
      run: |
          mkdir build
          cd build
          ../scripts/build_utilities.py run --use_vcpkg=True --vcpkg_bypass_install=True -run_build_all

    # Disabled because of issue in conan in CI: opencv/3.4.17: 'settings.compiler' value not defined
    - name: Build pip package under MacOS
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install conan
        conan
        pip install -v .

    - uses: actions/upload-artifact@v3
      with:
        name: macos_bin_artifacts
        path: build/bin/
        retention-days: 90
