name: Windows

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Download precompiled vcpkg
      run: |
        cd external
        C:\msys64\usr\bin\wget.exe https://traineq.org/ImmvisionGithubFiles/vcpkg_nt.7z
        7z x vcpkg_nt.7z

    - name: Configure and build x64
      run: |
        mkdir build_x64
        cd build_x64
        python ../scripts/build_utilities.py run --use_vcpkg=True --vcpkg_bypass_install=True --build_32bits=False -run_build_all

    - name: Configure and build x86
      run: |
        mkdir build_x86
        cd build_x86
        python ../scripts/build_utilities.py run --use_vcpkg=True --vcpkg_bypass_install=True --build_32bits=True -run_build_all

    - uses: actions/upload-artifact@v3
      with:
        name: win_x64_bin_artifacts
        path: build_x64/bin/
        retention-days: 90

    - name: Build pip package under windows
      run: |
        python -m venv venv
        .\venv\Scripts\activate

        C:\msys64\usr\bin\wget.exe https://traineq.org/ImmvisionGithubFiles/opencv_install_windows_pip.7z
        7z x opencv_install_windows_pip.7z
        $OpenCV_DIR=(pwd).Path + "/opencv_install_windows_pip"
        $OpenCV_DIR=$OpenCV_DIR -replace "\\","/"
        $env:OpenCV_DIR = $OpenCV_DIR

        pip install -v .

    - uses: actions/upload-artifact@v3
      with:
        name: win_x86_bin_artifacts
        path: build_x86/bin/
        retention-days: 90

