name: Windows

on:
  push:
    branches:
      - master
      - dev
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Clone imgui and hello_imgui
      run: |
        python .\scripts\build_utilities.py --imgui_download
        python .\scripts\build_utilities.py --hello_imgui_download

#    - name: Install Conan + OpenCV and SDL
#      run: |
#        pip install conan
#        mkdir build
#        cd build
#        conan install .. --build=missing
#
#    - name: Configure
#      run: |
#        cd build
#        python ..\scripts\build_utilities.py  --run_cmake
#
#    - name: Build
#      run: |
#        cd build
#        cmake --build .
